service: jobget

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jobgetwebsite-prod

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  environment:
    DEBUG: true
    ONLINE: 1
    MONGODB_ATLAS_CLUSTER_URI: ${ssm:MONGODB_ATLAS_CLUSTER_URI~true}

functions:
  createCompany:
    handler: api/app.createCompany
    events:
      - http:
          path: companies
          method: post
          cors: true
  createSubscriber:
    handler: api/app.createSubscriber
    events:
      - http:
          path: subscribers
          method: post
          cors: true