service: jobget

plugins:
  - serverless-finch


provider:
  name: aws
  runtime: nodejs6.10
  profile: prod
  awsKmsKeyArn: ${ssm:MDB_KEY}
  environment:
    DEBUG: false
    ONLINE: 1
    MONGODB_ATLAS_CLUSTER_URI: ${ssm:MDB_ATLAS_URI_ENCRYPTED}

custom:
  client:
    bucketName: jobgetwebsite-${self:provider.profile}

functions:
  createCompany:
    handler: api/app.createCompany
    events:
      - http:
          path: companies
          method: post
          cors: true
  createSubscriber:
    handler: api/app.createSubscriber
    events:
      - http:
          path: subscribers
          method: post
          cors: true