service: jobget

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jobgetwebsite

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DEBUG: true
    MONGODB_ATLAS_CLUSTER_URI: mongodb://lambdauser:lambdapass@cluster0-shard-00-00-wwwhr.mongodb.net:27017,cluster0-shard-00-01-wwwhr.mongodb.net:27017,cluster0-shard-00-02-wwwhr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin

functions:
  createCompany:
    handler: jobget-service/app.createCompany
    events:
      - http:
          path: companies
          method: post
          cors: true
  createSubscriber:
    handler: jobget-service/app.createSubscriber
    events:
      - http:
          path: subscribers
          method: post
          cors: true