service: jobget

plugins:
  - serverless-finch
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  awsKmsKeyArn: ${ssm:MDB_KEY}
  environment:
    DEBUG: false
    ONLINE: 1
    MONGODB_ATLAS_CLUSTER_URI: ${ssm:MDB_ATLAS_URI_ENCRYPTED}

custom:
  defaultStage: dev
  output:
    handle: scripts/output.process
    file: client/dist/js/apistring.json
  client:
    bucketName: jobget.com

functions:
  createCompany:
    handler: api/app.createCompany
    events:
      - http:
          path: companies
          method: post
          cors: true
  createSubscriber:
    handler: api/app.createSubscriber
    events:
      - http:
          path: subscribers
          method: post
          cors: true
